import * as Store from 'electron-store';
import { UserSettingStoreModel } from '../shared/models/user-setting.model';
import { mainApplicationStart } from './main-application-start';
import { handleOpenDirectoryEvent } from './events/open-directory.event';
import { handleUserSettingStoreEvents } from './events/user-setting.event';
import { handleDownloadLinkEvent } from './events/download-link-file.event';
import { handleDownloadModEvent } from './events/download-mod.event';
import { handleFileUnzipEvent } from './events/file-unzip.event';
import { handleClientModsEvent } from './events/client-mods.event';
import { handleServerModsEvent } from './events/server-mods.event';
import { handleWindowEvents } from './events/window.event';
import { autoUpdater } from 'electron-updater';
import { handleClearTemporaryDirectoryEvent } from './events/clear-temp.event';
import { handleThemeEvents } from './events/theme.event';
import { handleTutorialEvents } from './events/tutorial.event';
import { handleTarkovStartEvent } from './events/tarkov-start.event';
import { handleExperimentalFunctionsEvents } from './events/experimental-functions.event';
import { handleModLoadOrderEvents } from './events/mod-load-order.event';
import { handleUpdateModEvents } from './events/update-mod.event';
import { handleSptTagEvents } from './events/spt-tag.event';
import { handleSptVersionEvents } from './events/spt-version.event';
import { handleModCacheEvents } from './events/mod-list-cache.event';
import { handleIndexedModsEvents } from './events/indexed-mods.event';
import { toggleModStateEvent } from './events/toggle-mod-state.event';
import { handleModPageEvents } from './events/mod-page.event';
import { handleTempDownloadDirectoryEvents } from './events/temp-download-directory.event';
import { handleCheckInstalledEvents } from './events/toggle-check-installed.event';
import { initialize } from 'electron-log';
import { handleSharingModsEvents } from './events/export-mods.event';

initialize();

const isServe = process.argv.slice(1).some(val => val === '--serve');
const store = new Store<UserSettingStoreModel>();
void autoUpdater.checkForUpdatesAndNotify();

mainApplicationStart(isServe, store);
handleOpenDirectoryEvent(store);
handleDownloadLinkEvent();
handleDownloadModEvent();
handleFileUnzipEvent(isServe, store);
handleUserSettingStoreEvents(store);
handleClientModsEvent();
handleServerModsEvent();
handleWindowEvents();
handleClearTemporaryDirectoryEvent();
handleThemeEvents(store);
handleTutorialEvents(store);
handleTarkovStartEvent();
handleExperimentalFunctionsEvents(store);
handleModLoadOrderEvents();
handleUpdateModEvents(store);
handleSptTagEvents(store);
handleSptVersionEvents(store);
handleModCacheEvents(store);
handleIndexedModsEvents(store);
toggleModStateEvent(store);
handleModPageEvents();
handleTempDownloadDirectoryEvents(store);
handleCheckInstalledEvents(store);
handleSharingModsEvents();
