export const restrictedModList = [
  'SP-EFT Manager',
  'SPT',
  'SPT-INSTALLER',
  'SPT Mini-Launcher',
  'SPT Patcher',
  'SPT-Aki Profile Editor',
  'AKI Mods Installer',
  'Quick Launcher',
  'Ika SPT Launcher',
  'Discord RPC for SPT',
  'SPT Quick Launcher',
  'LOE (Load Order Editor)',
  'Unity Assets Bundle Extractor Avalonia',
  'Unity Bundle CAB-ID Changer',
  'DebugPlus',
  'Load Order Editor Drag-Drop',
  'AKI Mods Installer',
];
