import { handleOpenDirectoryEvent } from '../events/open-directory.event';
import { handleDownloadModEvent } from '../events/download-mod.event';
import { handleProcessDownloadLinkEvent } from '../events/handleProcessDownloadLinkEvent';
import { handleFileUnzipEvent } from '../events/file-unzip.event';
import { handleUserSettingStoreEvents } from '../events/user-setting.event';
import { handleClientModsEvent } from '../events/client-mods.event';
import { handleServerModsEvent } from '../events/server-mods.event';
import { handleWindowEvents } from '../events/window.event';
import { handleClearTemporaryDirectoryEvent } from '../events/clear-temp.event';
import { handleThemeEvents } from '../events/theme.event';
import { handleTutorialEvents } from '../events/tutorial.event';
import { handleTarkovStartEvent } from '../events/tarkov-start.event';
import { handleExperimentalFunctionsEvents } from '../events/experimental-functions.event';
import { handleModLoadOrderEvents } from '../events/mod-load-order.event';
import { handleUpdateModEvents } from '../events/update-mod.event';
import { handleSptTagEvents } from '../events/spt-tag.event';
import { handleSptVersionEvents } from '../events/spt-version.event';
import { handleModCacheEvents } from '../events/mod-list-cache.event';
import { toggleModStateEvent } from '../events/toggle-mod-state.event';
import { handleModPageEvents } from '../events/mod-page.event';
import { handleTempDownloadDirectoryEvents } from '../events/temp-download-directory.event';
import { handleCheckInstalledEvents } from '../events/toggle-check-installed.event';
import * as log from 'electron-log';
import { UserSettingStoreModel } from '../../shared/models/user-setting.model';
import * as Store from 'electron-store';

export function registerEventHandlers(store: Store<UserSettingStoreModel>, isServe: boolean): void {
  log.info('Registering IPC event handlers');
  handleOpenDirectoryEvent(store);
  handleDownloadModEvent();
  handleProcessDownloadLinkEvent();
  handleFileUnzipEvent(isServe);
  handleUserSettingStoreEvents(store);
  handleClientModsEvent();
  handleServerModsEvent();
  handleWindowEvents();
  handleClearTemporaryDirectoryEvent();
  handleThemeEvents(store);
  handleTutorialEvents(store);
  handleTarkovStartEvent();
  handleExperimentalFunctionsEvents(store);
  handleModLoadOrderEvents();
  handleUpdateModEvents(store);
  handleSptTagEvents(store);
  handleSptVersionEvents(store);
  handleModCacheEvents(store);
  toggleModStateEvent();
  handleModPageEvents();
  handleTempDownloadDirectoryEvents(store);
  handleCheckInstalledEvents(store);
  log.info('IPC event handlers registered');
}
