name: Release Electron Application

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Release Electron
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          build_script_name: "build:prod"
          args: --publish=always
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
